server:
  port: 8888
spring:
  application:
    name: dtmcli-spring-sample
  datasource:
    url: jdbc:mysql://en.dtm.pub:3306/dtm_barrier?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: '127.0.0.1:8848'
        service: ${spring.application.name}
        namespace: c3dc917d-906a-429d-90a9-85012b41014e
        username: nacos
        password: nacos
        register-enabled: true
feign:
  hystrix:
    enabled: true
dtm:
  service:
    name: dtmService
    registry-type: nacos
#debug: true